# Generated by Django 2.2 on 2019-05-21 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationName_text', models.CharField(max_length=200)),
                ('Application_url', models.URLField()),
                ('Application_logo_image', models.ImageField(upload_to='')),
                ('ApplicationCostPerUserPerYear', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompetenceName_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LearningOutcomeDescription_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName_text', models.CharField(max_length=200)),
                ('LinkedCompetence', models.ManyToManyField(to='LearningOutcomeSelector.Competences')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcomeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LearningOutcomeSubjectName_text', models.CharField(max_length=200)),
                ('LinkedOutcome', models.ManyToManyField(to='LearningOutcomeSelector.LearningOutcomes')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KnowledgeName_text', models.CharField(max_length=200)),
                ('LinkedSubject', models.ManyToManyField(to='LearningOutcomeSelector.LearningOutcomeSubject')),
            ],
        ),
        migrations.CreateModel(
            name='ExistingApplicationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationUser', models.CharField(max_length=200)),
                ('ApplicationUser_url', models.URLField()),
                ('LinkedApplication', models.ManyToManyField(to='LearningOutcomeSelector.Application')),
            ],
        ),
        migrations.AddField(
            model_name='competences',
            name='LinkedKnowledge',
            field=models.ManyToManyField(to='LearningOutcomeSelector.Knowledge'),
        ),
        migrations.CreateModel(
            name='ApplicationReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewPerson', models.CharField(max_length=200)),
                ('ReviewText', models.TextField(max_length=1000)),
                ('ReviewDate', models.DateTimeField(auto_now=True)),
                ('ReviewRating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('ReviewedApplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningOutcomeSelector.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeatureName_text', models.CharField(max_length=200)),
                ('LinkedSkills', models.ManyToManyField(to='LearningOutcomeSelector.Skills')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='LinkedApplicationFeatures',
            field=models.ManyToManyField(to='LearningOutcomeSelector.ApplicationFeatures'),
        ),
    ]
